version: '3.1'
services:
  db:
    image: mysql
    container_name: spring_boot_anime
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - developed_data:/var/lib/mysql

volumes:
  developed_data: